export const fortunes: { ko: string; en: string }[] = [
  { ko: "아름답고 사랑스러운 사람이 당신의 삶에 찾아올 것입니다.", en: "A beautiful and loving person will be coming into your life." },
  { ko: "당신이 꾸었던 꿈이 현실이 될 것입니다.", en: "A dream you have will come true." },
  { ko: "새로운 시작이 당신을 올바른 길로 이끌 것입니다.", en: "A fresh start will put you on your way." },
  { ko: "오래된 일들을 마무리하기에 좋은 때입니다.", en: "A good time to finish up old tasks." },
  { ko: "앞으로의 삶에 행복이 가득할 것입니다.", en: "A lifetime of happiness lies ahead of you." },
  { ko: "새로운 모험이 곧 시작됩니다.", en: "A new adventure is about to begin." },
  { ko: "말만 하고 행동하지 않는 사람은 잡초 가득한 정원과 같습니다.", en: "A person of words and not deeds is like a garden full of weeds." },
  { ko: "기분 좋은 놀라움이 당신을 기다리고 있습니다.", en: "A pleasant surprise is waiting for you." },
  { ko: "바꿀 수 없는 것을 받아들이면 마음이 편안해질 것입니다.", en: "Accept something that you cannot change, and you will feel better." },
  { ko: "모험이 곧 진정한 행복입니다.", en: "Adventure can be real happiness." },
  { ko: "모든 일은 쉬워지기 전에 어렵습니다.", en: "All things are difficult before they are easy." },
  { ko: "연민이 당신의 결정을 이끌게 하세요.", en: "Allow compassion to guide your decisions." },
  { ko: "중요한 사람이 당신을 지지해 줄 것입니다.", en: "An important person will offer you support." },
  { ko: "자신을 믿으면 성공할 수 있습니다.", en: "Be confident and you will succeed." },
  { ko: "변화가 당신의 삶에 일어나고 있습니다. 흐름을 따르세요!", en: "Change is happening in your life, so go with the flow!" },
  { ko: "호기심은 지루함을 없앱니다. 호기심 자체는 결코 사라지지 않습니다.", en: "Curiosity kills boredom. Nothing can kill curiosity." },
  { ko: "평정심을 유지하며 눈앞의 일에 집중하세요.", en: "Dedicate yourself with a calm mind to the task at hand." },
  { ko: "어려운 시간은 위대한 성취로 이어집니다.", en: "Difficult times lead to great achievements." },
  { ko: "두려워하지 말고 그 큰 발걸음을 내디디세요.", en: "Don't be afraid to take that big step." },
  { ko: "모든 꽃은 자신만의 때에 피어납니다.", en: "Every flower blooms in its own time." },
  { ko: "이제 모든 것이 당신에게로 올 것입니다.", en: "Everything will now come your way." },
  { ko: "위대한 것을 기대하면 위대한 것이 찾아옵니다.", en: "Expect great things and great things will come." },
  { ko: "실패는 더 잘할 수 있는 기회입니다.", en: "Failure is the chance to do better next time." },
  { ko: "꿈을 따르세요.", en: "Follow your dreams." },
  { ko: "행운은 준비된 자의 문을 두드립니다.", en: "Fortune knocks at the door of those who are prepared." },
  { ko: "듣는 것에서 지혜가 오고, 말하는 것에서 후회가 옵니다.", en: "From listening comes wisdom, and from speaking, repentance." },
  { ko: "마음을 가다듬으세요. 자신감이 당신을 이끌 것입니다.", en: "Get your mind set – confidence will lead you on." },
  { ko: "좋은 아이디어는 아이들처럼 자랄 수 있도록 해야 합니다.", en: "Good ideas, like children, should be allowed to grow." },
  { ko: "행운은 좋은 계획의 결과입니다.", en: "Good luck is the result of good planning." },
  { ko: "위대한 생각은 마음에서 나옵니다.", en: "Great thoughts come from the heart." },
  { ko: "행복한 소식이 당신에게 오고 있습니다.", en: "Happy news is on its way to you." },
  { ko: "아름다운 하루 되세요.", en: "Have a beautiful day." },
  { ko: "충분히 가지고 있다는 것을 아는 사람이 부자입니다.", en: "He who knows he has enough is rich." },
  { ko: "주려면 먼저 받아야 합니다.", en: "In order to take, one must first give." },
  { ko: "목적지보다 여정이 더 중요합니다.", en: "It's not the destination, it's the journey." },
  { ko: "태양을 바라보면 그림자는 보이지 않습니다.", en: "Keep your face to the sunshine and you cannot see the shadow." },
  { ko: "친절은 귀머거리도 듣고 장님도 볼 수 있는 언어입니다.", en: "Kindness is the language which the deaf can hear and the blind can see." },
  { ko: "웃음은 최고의 약입니다.", en: "Laughter is the best medicine." },
  { ko: "삶은 놀라움으로 가득 차 있습니다.", en: "Life is full of surprises." },
  { ko: "사랑이 코앞에 있습니다.", en: "Love is around the corner." },
  { ko: "사랑은 야생화와 같아서 가장 예상치 못한 곳에서 발견됩니다.", en: "Love is like wildflowers; it's often found in the most unlikely places." },
  { ko: "오늘을 새로운 삶의 첫 날로 만드세요.", en: "Make today the first day of the rest of your new life." },
  { ko: "충고는 많이 받지만 지혜로운 자만이 그것을 활용합니다.", en: "Many receive advice, only the wise profit from it." },
  { ko: "포기하지 마세요. 포기하지 않으면 실패가 아닙니다.", en: "Never give up. You're not a failure if you don't give up." },
  { ko: "의지 있는 마음에게 불가능한 것은 없습니다.", en: "Nothing is impossible to a willing heart." },
  { ko: "지금이 새로운 것을 시도할 좋은 때입니다.", en: "Now is a good time to try something new." },
  { ko: "기회는 사라지지 않습니다. 당신이 놓친 것은 다른 누군가가 가져갑니다.", en: "Opportunities are never lost; someone will take the ones you miss." },
  { ko: "인내는 기다리는 능력이 아니라 기다리는 동안 어떻게 행동하느냐입니다.", en: "Patience is not the ability to wait, but how you act while waiting." },
  { ko: "집착하지 않아도 될 싸움을 고르고, 이길 수 있는 싸움을 고르세요.", en: "Pick battles big enough to matter, small enough to win." },
  { ko: "앞으로 많은 즐거움이 기다리고 있습니다.", en: "Plan for many pleasures ahead." },
  { ko: "원하는 것은 기도하고, 필요한 것은 노력하세요.", en: "Pray for what you want, but work for the things you need." },
  { ko: "당신이 바라는 것을 기억하세요. 동의 없이는 아무도 당신을 열등하게 느끼게 할 수 없습니다.", en: "Remember, no one can make you feel inferior without your consent." },
  { ko: "행복을 다른 사람들과 나누세요.", en: "Share your happiness with others today." },
  { ko: "미소 지으면 세상도 함께 미소 짓습니다.", en: "Smile and the world smiles with you." },
  { ko: "누군가 당신에 대해 좋은 말을 하고 있습니다.", en: "Someone is speaking well of you." },
  { ko: "당신의 성공이 모두를 놀라게 할 것입니다.", en: "Your success will astonish everyone." },
  { ko: "성공은 목적지가 아니라 여정입니다.", en: "Success is a journey, not a destination." },
  { ko: "최고의 것은 아직 오지 않았습니다.", en: "The best is yet to come." },
  { ko: "적을 없애는 가장 좋은 방법은 친구로 만드는 것입니다.", en: "The best way to get rid of an enemy is to make a friend." },
  { ko: "첫 번째 발걸음이 가장 어렵습니다.", en: "The first step is the hardest." },
  { ko: "열심히 일할수록 더 운이 좋아집니다.", en: "The harder you work, the luckier you get." },
  { ko: "시작하는 것이 앞서가는 비결입니다.", en: "The secret of getting ahead is getting started." },
  { ko: "가장 간단한 답은 행동하는 것입니다.", en: "The simplest answer is to act." },
  { ko: "별들이 말합니다 — 사랑이 바로 코앞에 있습니다.", en: "The stars say — love is right around the corner." },
  { ko: "새 친구를 사귀기에 적절한 시기입니다.", en: "The time is right to make new friends." },
  { ko: "당신이 가진 것에 감사하지 않으면 가지지 못한 것에 화를 내는 것입니다.", en: "To be upset over what you don't have is to waste what you do have." },
  { ko: "직관을 믿으세요.", en: "Trust your intuition." },
  { ko: "부는 곧 당신을 찾아올 것입니다.", en: "Wealth awaits you very soon." },
  { ko: "잘 말하는 것보다 잘 행동하는 것이 낫습니다.", en: "Well done is better than well said." },
  { ko: "당신이 보는 것은 주로 당신이 무엇을 찾느냐에 달려 있습니다.", en: "What you see depends mainly on what you look for." },
  { ko: "나이와 함께 지혜가 찾아옵니다.", en: "With age comes wisdom." },
  { ko: "당신은 여러 방면에서 재능이 있습니다.", en: "You are talented in many ways." },
  { ko: "당신은 모든 상황의 주인입니다.", en: "You are the master of every situation." },
  { ko: "오늘 당신은 보상을 받을 자격이 있습니다.", en: "You deserve a reward today." },
  { ko: "당신은 더 높은 진실을 감지하고 아는 능력을 가지고 있습니다.", en: "You have an ability to sense and know a higher truth." },
  { ko: "당신만의 운명을 쓸 힘이 당신 안에 있습니다.", en: "You have the power to write your own fortune." },
  { ko: "당신의 개인적인 일에는 항상 행운이 함께할 것입니다.", en: "You will always have good luck in your personal affairs." },
  { ko: "당신의 인내와 이해심은 보답받을 것입니다.", en: "You will be rewarded for your patience and understanding." },
  { ko: "당신은 사랑에서 성공할 것입니다.", en: "You will be successful in love." },
  { ko: "이번 주 안에 좋은 소식을 듣게 될 것입니다.", en: "You will hear good news within the week." },
  { ko: "당신의 사랑하는 꿈이 이루어지고 있습니다.", en: "Your dearest dream is coming true." },
  { ko: "당신의 영원한 인내심은 조만간 보상받을 것입니다.", en: "Your everlasting patience will be rewarded sooner or later." },
  { ko: "당신의 미래는 밝습니다.", en: "Your future looks bright." },
  { ko: "당신의 노력이 곧 결실을 맺을 것입니다.", en: "Your hard work is about to pay off." },
  { ko: "당신의 마음은 진정한 행복을 끌어내는 장소입니다.", en: "Your heart is a place to draw true happiness." },
  { ko: "당신의 삶은 우연이 아니라 변화로 더 나아집니다.", en: "Your life does not get better by chance, it gets better by change." },
  { ko: "당신의 마음이 가장 큰 자산입니다.", en: "Your mind is your greatest asset." },
  { ko: "당신의 미소는 주변 모든 사람에게 행복을 줍니다.", en: "Your smile brings happiness to all those around you." },
  { ko: "당신의 재능은 인정받고 적절한 보상을 받을 것입니다.", en: "Your talents will be recognized and suitably rewarded." },
];
